In [33]:
# Load Datasets
import numpy as np
import pandas as pd
from sklearn.datasets import load_iris

iris_dataset = load_iris()


In [36]:
iris_dataset.keys()


dict_keys(['data', 'target', 'target_names', 'DESCR', 'feature_names', 'filename'])

In [51]:
print("Target:",iris_dataset.target)
print('Target_names:',iris_dataset.target_names)
print('Features_names:',iris_dataset.feature_names)

Target: [0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]
Target_names: ['setosa' 'versicolor' 'virginica']
Features_names: ['sepal length (cm)', 'sepal width (cm)', 'petal length (cm)', 'petal width (cm)']


In [44]:
#print(iris_dataset.DESCR)

In [43]:
print(iris_dataset.data.shape)

(150, 4)


In [50]:
print(iris_dataset.data[:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]


In [67]:
iris_dataframe = pd.DataFrame(np.c_[iris_dataset.data,iris_dataset.target],columns=list(iris_dataset.feature_names)+['target'])

In [68]:
from sklearn.model_selection import train_test_split
(X_train,X_test,y_train,y_test) = train_test_split(iris_dataset.data,iris_dataset.target,random_state=0)

In [69]:
print("X_train shape",X_train.shape)
print("y_train shape",y_train.shape)
print("X_test shape",X_test.shape)
print("y_test shape",y_test.shape)

X_train shape (112, 4)
y_train shape (112,)
X_test shape (38, 4)
y_test shape (38,)


In [73]:
from sklearn.neighbors import KNeighborsClassifier
knn = KNeighborsClassifier(n_neighbors = 1)

In [74]:
knn.fit(X_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=1, p=2,
                     weights='uniform')

In [75]:
knn.score(X_test,y_test)

0.9736842105263158

In [80]:
X_new = np.array([[4.3,9.2,1.1,4]])
pred = knn.predict(X_new)
print(iris_dataset.target_names[pred])

['setosa']


In [83]:
y_pred = knn.predict(X_test)
print("Predictions on test set",y_pred)

Predictions on test set [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0 2 1 0 2 2 1 0
 2]


In [85]:
print(np.mean(y_test==y_pred))

0.9736842105263158
