In [1]:
import numpy as np
import tensorflow.compat.v1 as tf
tf.disable_v2_behavior()

Instructions for updating:
non-resource variables are not supported in the long term


In [2]:
sess = tf.Session()
tens1 = tf.constant([[[1,2],[3,4]],[[5,6],[7,8]]])
print(sess.run(tens1))

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [3]:
print(sess.run(tens1)[0,1,1])

4


In [4]:
print(tens1)

Tensor("Const:0", shape=(2, 2, 2), dtype=int32)


In [5]:
arr = np.random.randn(32)
type(arr)

numpy.ndarray

In [6]:
x = tf.constant(arr,dtype=np.float32)
y = tf.constant([[1,2,3]])
z = tf.constant([[2],[3],[4]])
print(x,y,z)

Tensor("Const_1:0", shape=(32,), dtype=float32) Tensor("Const_2:0", shape=(1, 3), dtype=int32) Tensor("Const_3:0", shape=(3, 1), dtype=int32)


In [7]:
x_data = np.array([[1.,2.,3.],[4.,5.,6.]])
x = tf.convert_to_tensor(x_data,dtype=tf.float32)
print(x)

Tensor("Const_4:0", shape=(2, 3), dtype=float32)


In [8]:
sess.run(x)

array([[1., 2., 3.],
       [4., 5., 6.]], dtype=float32)

In [9]:
ses = tf.InteractiveSession()

In [10]:
x_data = np.array([[1.,2.,3.],[4.,5.,6.]])
x = tf.convert_to_tensor(x_data,dtype=tf.float32)
print(x)

Tensor("Const_5:0", shape=(2, 3), dtype=float32)


In [11]:
c = tf.add(y,z)
sess.run(c)

array([[3, 4, 5],
       [4, 5, 6],
       [5, 6, 7]])

In [12]:
c = tf.matmul(y,z)
sess.run(c)

array([[20]])

In [13]:
tf.Graph.version

In [14]:
tf.placeholder(dtype=np.int32,shape=(3,2))

<tf.Tensor 'Placeholder:0' shape=(3, 2) dtype=int32>

In [15]:
b = tf.Variable(tf.zeros([1000]))

In [16]:
g = tf.Graph()
with g.as_default():
    sess = tf.Session()
    w_m = tf.Variable(tf.zeros([10,5]))
    x_v = tf.placeholder(tf.float32,[None,10])
    result = tf.matmul(x_v,w_m)
print(g.as_graph_def())

node {
  name: "zeros"
  op: "Const"
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "value"
    value {
      tensor {
        dtype: DT_FLOAT
        tensor_shape {
          dim {
            size: 10
          }
          dim {
            size: 5
          }
        }
        float_val: 0.0
      }
    }
  }
}
node {
  name: "Variable"
  op: "VariableV2"
  attr {
    key: "container"
    value {
      s: ""
    }
  }
  attr {
    key: "dtype"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "shape"
    value {
      shape {
        dim {
          size: 10
        }
        dim {
          size: 5
        }
      }
    }
  }
  attr {
    key: "shared_name"
    value {
      s: ""
    }
  }
}
node {
  name: "Variable/Assign"
  op: "Assign"
  input: "Variable"
  input: "zeros"
  attr {
    key: "T"
    value {
      type: DT_FLOAT
    }
  }
  attr {
    key: "_class"
    value {
      list {
        s: "loc:@Variable"
      }
    }


In [17]:
sess = tf.InteractiveSession()
x = tf.constant([[2,3,5,1],[0,0,1,2],[8,-1,2,0],[1,-3,3,1]])
y = tf.constant([[2,-3,0,1],[3,0,1,2],[2,-1,2,0],[1,0,0,1]])
floatx = tf.constant([[2,3,5,1],[0,0,1,2],[8,-1,2,0],[1,-3,3,1]],dtype=np.float32)


C:\Users\devro\AppData\Roaming\Python\Python38\site-packages\tensorflow\python\client\session.py:1761: UserWarning: An interactive session is already active. This can cause out-of-memory errors in some cases. You must explicitly call `InteractiveSession.close()` to release resources held by the other session(s).
  warnings.warn('An interactive session is already active. This can '


In [18]:
print(x.eval(),y,floatx)

[[ 2  3  5  1]
 [ 0  0  1  2]
 [ 8 -1  2  0]
 [ 1 -3  3  1]] Tensor("Const_7:0", shape=(4, 4), dtype=int32) Tensor("Const_8:0", shape=(4, 4), dtype=float32)


In [19]:
tf.transpose(x).eval()

array([[ 2,  0,  8,  1],
       [ 3,  0, -1, -3],
       [ 5,  1,  2,  3],
       [ 1,  2,  0,  1]])

In [20]:
tf.matmul(x,y).eval()

array([[ 24, -11,  13,   9],
       [  4,  -1,   2,   2],
       [ 17, -26,   3,   6],
       [  0,  -6,   3,  -4]])

In [21]:
tf.matrix_determinant(floatx).eval()

-301.00003

In [22]:
tf.matrix_inverse(floatx).eval()

array([[-0.02325582,  0.04651163,  0.13953489, -0.06976745],
       [ 0.11960132,  0.04651164, -0.00332226, -0.2126246 ],
       [ 0.15282393, -0.1627907 , -0.05980067,  0.17275748],
       [-0.07641196,  0.5813953 ,  0.02990033, -0.08637874]],
      dtype=float32)

In [23]:
floatx.eval()

array([[ 2.,  3.,  5.,  1.],
       [ 0.,  0.,  1.,  2.],
       [ 8., -1.,  2.,  0.],
       [ 1., -3.,  3.,  1.]], dtype=float32)

In [24]:
tf.matrix_solve(floatx,[[1],[1],[1],[1]]).eval()

array([[ 0.09302326],
       [-0.04983387],
       [ 0.10299002],
       [ 0.44850498]], dtype=float32)

In [25]:
x.eval()

array([[ 2,  3,  5,  1],
       [ 0,  0,  1,  2],
       [ 8, -1,  2,  0],
       [ 1, -3,  3,  1]])

In [26]:
tf.reduce_prod(x,reduction_indices=1).eval()

array([30,  0,  0, -9])

In [27]:
tf.reduce_max(x,reduction_indices=1).eval()

array([5, 2, 8, 3])

In [28]:
tf.reduce_min(x,reduction_indices=1).eval()

array([ 1,  0, -1, -3])

In [29]:
tf.reduce_mean(x,reduction_indices=1).eval()

array([2, 0, 2, 0])

In [30]:
seg_ids = tf.constant([0,1,1,2,2])
tens1 =  tf.constant([[2, 5, 3, -5],[0, 3,-2, 5],[4, 3, 5, 3],[6, 1,
4, 0],[6, 1, 4, 0]]) 
tf.segment_sum(tens1,seg_ids).eval()

array([[ 2,  5,  3, -5],
       [ 4,  6,  3,  8],
       [12,  2,  8,  0]])

In [31]:
tf.shape(x).eval()

array([4, 4])

In [32]:
tf.size(x).eval()

16

In [33]:
tf.rank(x).eval()

2

In [34]:
x.eval()

array([[ 2,  3,  5,  1],
       [ 0,  0,  1,  2],
       [ 8, -1,  2,  0],
       [ 1, -3,  3,  1]])

In [35]:
tf.reshape(x,(8,2)).eval()

array([[ 2,  3],
       [ 5,  1],
       [ 0,  0],
       [ 1,  2],
       [ 8, -1],
       [ 2,  0],
       [ 1, -3],
       [ 3,  1]])

In [36]:
tf.expand_dims(x,1)

<tf.Tensor 'ExpandDims:0' shape=(4, 1, 4) dtype=int32>

In [37]:
img = np.random.randint(255,size=(300,300))
img

array([[  0, 160, 142, ...,  15,  27, 181],
       [223,   4, 114, ..., 222, 163, 212],
       [174, 102,  21, ..., 168,  34,  42],
       ...,
       [ 69, 228,  75, ..., 162, 210, 184],
       [ 12,  99, 109, ..., 241, 176, 144],
       [205, 127,  36, ..., 230, 227, 120]])

In [38]:
a = tf.convert_to_tensor(img,dtype=np.uint8)

In [39]:
a

<tf.Tensor 'Const_11:0' shape=(300, 300) dtype=uint8>

In [40]:
a.eval()

array([[  0, 160, 142, ...,  15,  27, 181],
       [223,   4, 114, ..., 222, 163, 212],
       [174, 102,  21, ..., 168,  34,  42],
       ...,
       [ 69, 228,  75, ..., 162, 210, 184],
       [ 12,  99, 109, ..., 241, 176, 144],
       [205, 127,  36, ..., 230, 227, 120]], dtype=uint8)

In [42]:
import cv2
cv2.imshow("s",a.eval())
cv2.waitKey()

-1