In [1]:
%matplotlib notebook
import numpy as np
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
from sklearn.model_selection import train_test_split
from sklearn.datasets import load_digits
datasets = load_digits()
X,y = datasets.data,datasets.target
for class_name,class_count in zip(datasets.target_names,np.bincount(datasets.target)):
    print(class_name,class_count)

0 178
1 182
2 177
3 183
4 181
5 182
6 181
7 179
8 174
9 180


In [2]:
y_binary_imbalanced = y.copy()
y_binary_imbalanced[y_binary_imbalanced!=1]=0
print("Real y:",y[:30])
print("Imbalanced y:",y_binary_imbalanced[:30])


Real y: [0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9 0 1 2 3 4 5 6 7 8 9]
Imbalanced y: [0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 1 0 0 0 0 0 0 0 0]


In [3]:
np.bincount(y_binary_imbalanced)

array([1615,  182], dtype=int64)

In [4]:
X_train,X_test,y_train,y_test = train_test_split(X,y_binary_imbalanced,random_state=0)

from sklearn.svm import SVC
svm = SVC(kernel='rbf',C=1).fit(X_train,y_train)
svm.score(X_test,y_test)

0.9955555555555555

In [5]:
from sklearn.dummy import DummyClassifier
dummy_majority = DummyClassifier(strategy='most_frequent').fit(X_train,y_train)
y_dummy_predictions = dummy_majority.predict(X_test)
y_dummy_predictions


array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [6]:
dummy_majority.score(X_test,y_test)


0.9044444444444445

In [7]:
svm = SVC(kernel='linear',C=1).fit(X_train,y_train)
svm.score(X_test,y_test)

0.9777777777777777

In [8]:
from sklearn.metrics import confusion_matrix
dummy_majority = DummyClassifier(strategy='most_frequent').fit(X_train,y_train)
dummy_predicted = dummy_majority.predict(X_test)
confusion = confusion_matrix(y_test,dummy_predicted)
print("Confusion Matrix for Dummy Classifier based on Most Frequent class:\n",confusion)

Confusion Matrix for Dummy Classifier based on Most Frequent class:
 [[407   0]
 [ 43   0]]


In [9]:
dummy_prop = DummyClassifier(strategy='stratified').fit(X_train,y_train)
dummy_prop_predicted = dummy_prop.predict(X_test)
confusion = confusion_matrix(y_test,dummy_prop_predicted)
print("Confusion Matrix for Dummy Classifier based on Random Classification:\n",confusion)

Confusion Matrix for Dummy Classifier based on Random Classification:
 [[360  47]
 [ 40   3]]


In [10]:
svm = SVC(kernel='linear',C=1).fit(X_train,y_train)
svm_predicted = svm.predict(X_test)
confusion = confusion_matrix(y_test,svm_predicted)
print("Confusion Matrix for Linear SVM Classifier:\n",confusion)

Confusion Matrix for Linear SVM Classifier:
 [[402   5]
 [  5  38]]


In [11]:
from sklearn.linear_model import LogisticRegression
lr = LogisticRegression().fit(X_train,y_train)
lr_predicted = lr.predict(X_test)
confusion = confusion_matrix(y_test,lr_predicted)
print("Confusion Matrix for Logistic Regression:\n",confusion)

Confusion Matrix for Logistic Regression:
 [[401   6]
 [  8  35]]


C:\Users\devro\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


In [12]:
from sklearn.tree import DecisionTreeClassifier
dt = DecisionTreeClassifier(max_depth=2).fit(X_train,y_train)
dt_predicted = dt.predict(X_test)
confusion = confusion_matrix(y_test,dt_predicted)
print("Confusion Matrix for DecisionTreeClassifier:\n",confusion)

Confusion Matrix for DecisionTreeClassifier:
 [[400   7]
 [ 17  26]]


In [13]:
from sklearn.metrics import accuracy_score,precision_score,recall_score,f1_score
print("Accuracy Score:{:.3f}".format(accuracy_score(y_test,dt_predicted)))
print("Precision:{:.3f}".format(precision_score(y_test,dt_predicted)))
print("Recall:{:.3f}".format(recall_score(y_test,dt_predicted)))
print("F1 Score:{:.3f}".format(f1_score(y_test,dt_predicted)))

Accuracy Score:0.947
Precision:0.788
Recall:0.605
F1 Score:0.684


In [14]:
from sklearn.metrics import classification_report
print(classification_report(y_test,dt_predicted,target_names=['not 1','1']))

              precision    recall  f1-score   support

       not 1       0.96      0.98      0.97       407
           1       0.79      0.60      0.68        43

    accuracy                           0.95       450
   macro avg       0.87      0.79      0.83       450
weighted avg       0.94      0.95      0.94       450



In [15]:
print("Random Classifier Report:\n",classification_report(y_test,dummy_prop_predicted,target_names=['not 1','1']))
print("SVM Classifier Report:\n",classification_report(y_test,svm_predicted,target_names=['not 1','1']))
print("Logistic Classifier Report:\n",classification_report(y_test,lr_predicted,target_names=['not 1','1']))
print("Decision Tree Classifier Report:\n",classification_report(y_test,dt_predicted,target_names=['not 1','1']))

Random Classifier Report:
               precision    recall  f1-score   support

       not 1       0.90      0.88      0.89       407
           1       0.06      0.07      0.06        43

    accuracy                           0.81       450
   macro avg       0.48      0.48      0.48       450
weighted avg       0.82      0.81      0.81       450

SVM Classifier Report:
               precision    recall  f1-score   support

       not 1       0.99      0.99      0.99       407
           1       0.88      0.88      0.88        43

    accuracy                           0.98       450
   macro avg       0.94      0.94      0.94       450
weighted avg       0.98      0.98      0.98       450

Logistic Classifier Report:
               precision    recall  f1-score   support

       not 1       0.98      0.99      0.98       407
           1       0.85      0.81      0.83        43

    accuracy                           0.97       450
   macro avg       0.92      0.90      0.91     

In [16]:
X_train,X_test,y_train,y_test = train_test_split(X,y_binary_imbalanced,random_state=0)
y_scores_lr = lr.fit(X_train,y_train).decision_function(X_test)
y_score_list = list(zip(y_test[:20],y_scores_lr[:20]))
y_score_list



C:\Users\devro\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[(0, -29.828772009991667),
 (0, -19.382801050061957),
 (0, -29.198642696254918),
 (0, -21.746386043966467),
 (0, -22.642356868158288),
 (0, -11.805856133622399),
 (1, 6.4959992614899065),
 (0, -23.354667312206328),
 (0, -27.544163114762792),
 (0, -26.888205434887926),
 (0, -31.863221446983143),
 (0, -22.486035793478106),
 (0, -25.318055296874483),
 (0, -13.384477072076102),
 (0, -13.565675488053238),
 (0, -13.308303778707845),
 (1, 12.181083900744412),
 (0, -34.36237264138141),
 (0, -13.231580938636178),
 (0, -29.594027196661564)]

In [17]:
y_proba_lr = lr.fit(X_train,y_train).predict_proba(X_test)
y_proba_list = list(zip(y_test[:20],y_proba_lr[:20,1]))
y_proba_list

C:\Users\devro\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


[(0, 1.1105264686148249e-13),
 (0, 3.820818944672015e-09),
 (0, 2.0854059002182867e-13),
 (0, 3.594715626765122e-10),
 (0, 1.4674028384498448e-10),
 (0, 7.4606829899019575e-06),
 (1, 0.9984928089457435),
 (0, 7.197751680476795e-11),
 (0, 1.0907417846580064e-12),
 (0, 2.101845316534823e-12),
 (0, 1.4520405673135273e-14),
 (0, 1.7156896641113812e-10),
 (0, 1.010434792708349e-11),
 (0, 1.5388447107086222e-06),
 (0, 1.2838120115491663e-06),
 (0, 1.6606434016199439e-06),
 (1, 0.9999948735083789),
 (0, 1.1929196069321548e-15),
 (0, 1.7930674747929662e-06),
 (0, 1.4043562493363103e-13)]

In [18]:
from sklearn.metrics import precision_recall_curve
precision,recall,thresholds = precision_recall_curve(y_test,y_scores_lr)
closest_zero = np.argmin(np.abs(thresholds))
closest_zero_p = precision[closest_zero]
closest_zero_r = recall[closest_zero]

plt.figure()
plt.xlim([0.0,1.01])
plt.ylim([0.0,1.01])
plt.plot(precision,recall,label='Precision-Recall Curve')
plt.plot(closest_zero_p,closest_zero_r,'o',markersize=12,fillstyle='none',c='r',mew=3)
plt.xlabel('Precision',fontsize=16)
plt.ylabel('Recall',fontsize=16)
plt.axes().set_aspect('equal')
plt.show()

<IPython.core.display.Javascript object>

<ipython-input-18-32696904e315>:14: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.axes().set_aspect('equal')


In [19]:
from sklearn.metrics import roc_curve,auc
X_train,X_test,y_train,y_test = train_test_split(X,y_binary_imbalanced,random_state=0)
y_score_lr = lr.fit(X_train,y_train).decision_function(X_test)
fpr_lr,tpr_lr,_ =roc_curve(y_test,y_score_lr)
roc_auc_lr = auc(fpr_lr,tpr_lr)

plt.figure()
plt.xlim([0.0,1.01])
plt.ylim([0.0,1.01])
plt.plot(fpr_lr,tpr_lr,lw=3,label='LogRegr ROC curve (area={:.2f})'.format(roc_auc_lr))
plt.xlabel("False Positive Rate",fontsize=16)
plt.ylabel("True Positive Rate",fontsize=16)
plt.title('ROC curve(1-10 digits classifier)',fontsize=16)
plt.legend(loc='lower right',fontsize=13)
plt.plot([0,1],[0,1],color='navy',lw=3,linestyle='--')
plt.axes().set_aspect('equal')
plt.show()


C:\Users\devro\AppData\Roaming\Python\Python38\site-packages\sklearn\linear_model\_logistic.py:763: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


<IPython.core.display.Javascript object>

<ipython-input-19-c35b1b4354a6>:16: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.axes().set_aspect('equal')


In [20]:
from matplotlib import cm
plt.figure()
plt.xlim([0.0,1.01])
plt.ylim([0.0,1.01])
for g in [0.01,0.1,0.2,1]:
    svm = SVC(gamma=g).fit(X_train,y_train)
    y_score_svm = svm.decision_function(X_test)
    fpr_svm,tpr_svm,_= roc_curve(y_test,y_score_svm)
    roc_auc_svm = auc(fpr_svm,tpr_svm)
    accuracy_svm = svm.score(X_test,y_test)
    print('Gamma = {:.3f}, Accuracy = {:.3f}, AUC ={:.3f}'.format(g,accuracy_svm,roc_auc_svm))
    plt.plot(fpr_svm,tpr_svm,lw=3,alpha=0.7,label='SVM(gamma={:.2f},area={:.2f})'.format(g,roc_auc_svm))
plt.xlabel('False Positive Rate',fontsize=16)
plt.ylabel('True Positive Rate',fontsize=16)
plt.legend(loc='lower right',fontsize=11)
plt.title("ROC(1-10 digit Classifier)",fontsize=16)
plt.axes().set_aspect('equal')
plt.show()
    

<IPython.core.display.Javascript object>

Gamma = 0.010, Accuracy = 0.909, AUC =1.000
Gamma = 0.100, Accuracy = 0.904, AUC =0.982
Gamma = 0.200, Accuracy = 0.904, AUC =0.665
Gamma = 1.000, Accuracy = 0.904, AUC =0.500


<ipython-input-20-254e1a8ca149>:17: MatplotlibDeprecationWarning: Adding an axes using the same arguments as a previous axes currently reuses the earlier instance.  In a future version, a new instance will always be created and returned.  Meanwhile, this warning can be suppressed, and the future behavior ensured, by passing a unique label to each axes instance.
  plt.axes().set_aspect('equal')


In [21]:
from sklearn.metrics import confusion_matrix
dataset = load_digits()
X,y = dataset.data,dataset.target
X_train_mc,X_test_mc,y_train_mc,y_test_mc = train_test_split(X,y,random_state=0) 

svm = SVC(kernel='linear').fit(X_train_mc,y_train_mc)
svm_predicted_mc = svm.predict(X_test_mc)
confusion_mc = confusion_matrix(y_test_mc,svm_predicted_mc)
df_cm = pd.DataFrame(confusion_mc,index=[i for i in range(0,10)],columns=[i for i in range(0,10)])
plt.figure(figsize=(5.5,4))
sns.heatmap(df_cm,annot=True)
plt.title('SVM RBF kernel\nAccuracy:{:.3f}'.format(accuracy_score(y_test_mc,svm_predicted_mc)))
plt.ylabel("True Label")
plt.xlabel("Predicted Label")



<IPython.core.display.Javascript object>

Text(0.5, 14.722222222222216, 'Predicted Label')

In [22]:
print(classification_report(y_test_mc,svm_predicted_mc))

              precision    recall  f1-score   support

           0       1.00      1.00      1.00        37
           1       0.91      0.98      0.94        43
           2       0.98      1.00      0.99        44
           3       0.98      0.96      0.97        45
           4       0.97      1.00      0.99        38
           5       0.98      0.98      0.98        48
           6       1.00      0.98      0.99        52
           7       1.00      0.98      0.99        48
           8       0.94      0.92      0.93        48
           9       0.96      0.94      0.95        47

    accuracy                           0.97       450
   macro avg       0.97      0.97      0.97       450
weighted avg       0.97      0.97      0.97       450



In [23]:
print('Micro-averaged precision = {:.2f} (treat instances equally)'
      .format(precision_score(y_test_mc, svm_predicted_mc, average = 'micro')))
print('Macro-averaged precision = {:.2f} (treat classes equally)'
      .format(precision_score(y_test_mc, svm_predicted_mc, average = 'macro')))

Micro-averaged precision = 0.97 (treat instances equally)
Macro-averaged precision = 0.97 (treat classes equally)


In [24]:
print("Micro-averaged f1 score = {:.2f} (treat instances equally)"
     .format(f1_score(y_test_mc,svm_predicted_mc,average='micro')))
print("Macro-averaged f1 score = {:.2f} (treat classes equally)"
     .format(f1_score(y_test_mc,svm_predicted_mc,average='macro')))

Micro-averaged f1 score = 0.97 (treat instances equally)
Macro-averaged f1 score = 0.97 (treat classes equally)


In [25]:
from sklearn import datasets
from sklearn.linear_model import LinearRegression
from sklearn.metrics import r2_score,mean_squared_error
from sklearn.dummy import DummyRegressor

diabetes = datasets.load_diabetes()
X = diabetes.data[:,None,6]
y = diabetes.target

X_train,X_test,y_train,y_test = train_test_split(X,y,random_state=0)

lm = LinearRegression().fit(X_train,y_train)
lm_dummy_mean = DummyRegressor(strategy='mean').fit(X_train,y_train)
y_predict = lm.predict(X_test)
y_predict_dummy = lm_dummy_mean.predict(X_test)
print("Linear model Coefficients:",lm.coef_)
print("Mean Squared error(Dummy): {:.2f}".format(mean_squared_error(y_test,y_predict_dummy)))
print("Mean Squared error(Linear): {:.2f}".format(mean_squared_error(y_test,y_predict)))

print("R2 Score(Dummy): {:.2f}".format(r2_score(y_test,y_predict_dummy)))
print("R2 Score(Linear): {:.2f}".format(r2_score(y_test,y_predict)))

plt.scatter(X_test,y_test,color='black')
plt.plot(X_test,y_predict,color='green',linewidth=2,label='Linear')
plt.plot(X_test,y_predict_dummy,color='red',linestyle='dashed',linewidth=2,label='Dummy')
plt.show()

Linear model Coefficients: [-698.80206267]
Mean Squared error(Dummy): 4965.13
Mean Squared error(Linear): 4646.74
R2 Score(Dummy): -0.00
R2 Score(Linear): 0.06


In [26]:
from sklearn.model_selection import cross_val_score
from sklearn.svm import SVC
dataset = load_digits()
X,y = dataset.data,dataset.target == 1
clf = SVC(kernel='linear',C=1)

print("Cross Validation Score :",cross_val_score(clf,X,y,cv=5))
print("Cross Validation Score(ROC_AUC) :",cross_val_score(clf,X,y,cv=5,scoring='roc_auc'))
print("Cross Validation Score(Recall) :",cross_val_score(clf,X,y,cv=5,scoring='recall'))

Cross Validation Score : [0.91944444 0.98611111 0.97214485 0.97493036 0.96935933]
Cross Validation Score(ROC_AUC) : [0.9641871  0.9976571  0.99372205 0.99699002 0.98675611]
Cross Validation Score(Recall) : [0.81081081 0.89189189 0.83333333 0.83333333 0.83333333]


In [27]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
from sklearn.metrics import roc_auc_score

dataset = load_digits()
X, y = dataset.data, dataset.target == 1
X_train, X_test, y_train, y_test = train_test_split(X, y, random_state=0)

clf = SVC(kernel='rbf')
grid_values = {'gamma': [0.001, 0.01, 0.05, 0.1, 1, 10, 100]}

# default metric to optimize over grid parameters: accuracy
grid_clf_acc = GridSearchCV(clf, param_grid = grid_values)
grid_clf_acc.fit(X_train, y_train)
y_decision_fn_scores_acc = grid_clf_acc.decision_function(X_test) 

print('Grid best parameter (max. accuracy): ', grid_clf_acc.best_params_)
print('Grid best score (accuracy): ', grid_clf_acc.best_score_)

# alternative metric to optimize over grid parameters: AUC
grid_clf_auc = GridSearchCV(clf, param_grid = grid_values, scoring = 'roc_auc')
grid_clf_auc.fit(X_train, y_train)
y_decision_fn_scores_auc = grid_clf_auc.decision_function(X_test) 

print('Test set AUC: ', roc_auc_score(y_test, y_decision_fn_scores_auc))
print('Grid best parameter (max. AUC): ', grid_clf_auc.best_params_)
print('Grid best score (AUC): ', grid_clf_auc.best_score_)


Grid best parameter (max. accuracy):  {'gamma': 0.001}
Grid best score (accuracy):  0.9985157648354676
Test set AUC:  0.99982858122393
Grid best parameter (max. AUC):  {'gamma': 0.001}
Grid best score (AUC):  1.0


In [28]:
from sklearn.metrics.scorer import SCORERS
print(sorted(list(SCORERS.keys())))

ModuleNotFoundError: No module named 'sklearn.metrics.scorer'

In [32]:
import pandas as pd
pd.DataFrame.corr?